### ISSUE TITLE
Flags or environment variables are not being enforced

### ISSUE THREAD

**Issue by nc-ruth** [TierMobility/boring-registry#139]
Hi,

I have set up a minio instance locally and trying to upload modules to it via boring-registry.

I have the following .hcl file in the module folder:
```
metadata {
  namespace = "tier"
  name      = "tls-private-key"
  provider = "aws"
  version   = "0.1.0"
}
```

But whenever I run the following command:

```
boring-registry upload module   --storage-s3-bucket=terraform-registry-test \
  --storage-s3-region=eu-east-1 \
  --storage-s3-pathstyle=true \
  --storage-s3-endpoint=http://localhost:9000 .
```

It comes with the following error:
`operation error S3: CreateMultipartUpload, exceeded maximum number of attempts, 3, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: i/o timeout: failed to upload module
`

**Comment by oliviermichaelis** [comment]
The error indicates that the AWS client tried all authentication methods and tries to use the EC2 IMDS role as a last resort, which ultimately failed.

I could reproduce the error with the following `docker-compose.yaml` file:
```yaml
version: '3.7'

services:
  minio1:
    image: quay.io/minio/minio:RELEASE.2023-08-09T23-30-22Z
    command: server --console-address ":9001" http://minio1/data{1...2}
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2
volumes:
  data1-1:
  data1-2:
```

Uploading modules failed. What I had to do was to create an access key in MinIO. I could then pass the access key and the secret key as environment variables to the `upload` command:
```bash
$ AWS_ACCESS_KEY_ID=myAccessKeyId AWS_SECRET_ACCESS_KEY=mySecretAccessKey go run ./... upload module --storage-s3-bucket=terraform-registry-test --storage-s3-region=eu-east-1 --storage-s3-pathstyle=true --storage-s3-endpoint=http://localhost:9000 /path/to/my/modules
```

Let me know if that helps :)
